"""Add users and orders

Revision ID: a2bed87fd63a
Revises: 
Create Date: 2025-12-26 20:52:21.788697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2bed87fd63a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_jwt_email'), table_name='users_jwt')
    op.drop_index(op.f('ix_users_jwt_id'), table_name='users_jwt')
    op.drop_table('users_jwt')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'hashed_password')
    op.create_table('users_jwt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_jwt_pkey'))
    )
    op.create_index(op.f('ix_users_jwt_id'), 'users_jwt', ['id'], unique=False)
    op.create_index(op.f('ix_users_jwt_email'), 'users_jwt', ['email'], unique=True)
    # ### end Alembic commands ###
